## Purpose of notebook

1. To explore how to use yfinance potentially to get data for fundamental analysis
2. Also to explore for model training (the time series forecasting models)

In [1]:
import yfinance as yf
import pandas as pd
import numpy as np

### Export S&P 500 data

In [ ]:
# get S&P 500 data and export to csv
data = yf.Ticker("^SPX")
prices = data.history(period='max', interval='1d')
prices.index = pd.to_datetime(prices.index, format='%Y-%m-%d')
prices.index = prices.index.strftime('%Y-%m-%d')

In [12]:
prices

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
1927-12-30,17.660000,17.660000,17.660000,17.660000,0,0.0,0.0
1928-01-03,17.760000,17.760000,17.760000,17.760000,0,0.0,0.0
1928-01-04,17.719999,17.719999,17.719999,17.719999,0,0.0,0.0
1928-01-05,17.549999,17.549999,17.549999,17.549999,0,0.0,0.0
1928-01-06,17.660000,17.660000,17.660000,17.660000,0,0.0,0.0
...,...,...,...,...,...,...,...
2025-04-28,5529.220215,5553.660156,5468.640137,5528.750000,4257880000,0.0,0.0
2025-04-29,5508.870117,5571.950195,5505.700195,5560.830078,4747150000,0.0,0.0
2025-04-30,5499.439941,5581.839844,5433.240234,5569.060059,5449490000,0.0,0.0
2025-05-01,5625.140137,5658.910156,5597.350098,5604.140137,4935270000,0.0,0.0
2025-05-02,5645.879883,5700.700195,5642.279785,5686.669922,4854380000,0.0,0.0

In [13]:
prices.to_csv('../../data/sp500.csv')

In [14]:
# load list of companies in S&P 500
def load_data(url):
    html = pd.read_html(url, header=0)
    return html

url = 'https://en.wikipedia.org/wiki/List_of_S%26P_500_companies'
df = load_data(url)[0]

In [16]:
# export df as a csv file as well so that we can perform clustering analysis (using the industrial and sub industry data)
df.to_csv('../../data/sp500_companies_sector.csv')

In [17]:
companies = df['Symbol'].tolist()
# replace fullstops with dashes instead
companies = [c.replace('.', '-') for c in companies]

## Get the price data of all stocks in S&P 500

In [19]:
data = yf.Tickers(companies)

In [ ]:
all_data = data.history(period='10y')

[*********************100%***********************]  503 of 503 completed

In [29]:
all_data

Price            Close                                                  \
Ticker               A        AAPL        ABBV        ABNB         ABT
Date
2015-05-04   38.636948   28.742270   42.641659         NaN   38.864830
2015-05-05   38.314510   28.094624   42.101055         NaN   38.740784
2015-05-06   38.314510   27.918198   42.153805         NaN   38.484444
2015-05-07   38.507973   28.090872   42.654850         NaN   38.451374
2015-05-08   39.152843   28.620131   43.010845         NaN   39.336151
...                ...         ...         ...         ...         ...
2025-04-28  106.870003  210.139999  192.339996  123.300003  129.529999
2025-04-29  107.459999  211.210007  193.509995  125.489998  130.500000
2025-04-30  107.599998  212.500000  195.100006  121.919998  130.750000
2025-05-01  106.459999  213.320007  193.339996  124.010002  130.880005
2025-05-02  108.629997  205.350006  198.470001  125.260002  132.820007

Price                                                                 ...  \
Ticker           ACGL         ACN        ADBE         ADI        ADM  ...
Date                                                                  ...
2015-05-04  19.534626   80.176292   75.849998   51.467667  37.660133  ...
2015-05-05  19.480742   79.505646   75.000000   50.263374  37.682594  ...
2015-05-06  19.559982   78.953804   74.480003   50.157574  37.375744  ...
2015-05-07  19.791368   80.218742   74.730003   50.483074  37.660133  ...
2015-05-08  19.864269   81.407333   76.309998   51.036400  38.356174  ...
...               ...         ...         ...         ...        ...  ...
2025-04-28  91.190002  293.250000  368.619995  193.720001  48.049999  ...
2025-04-29  92.389999  298.470001  370.980011  192.669998  47.779999  ...
2025-04-30  90.680000  299.149994  374.980011  194.919998  47.750000  ...
2025-05-01  89.669998  300.529999  374.630005  193.740005  47.580002  ...
2025-05-02  92.480003  305.329987  380.869995  198.589996  47.849998  ...

Price       Volume                                                          \
Ticker         WTW       WY     WYNN      XEL       XOM      XYL       YUM
Date
2015-05-04  474366  5075000  4627000  3386200  10343700   920200  14124910
2015-05-05  373234  3103800  2304500  3824900  11895000   946900   6820629
2015-05-06  289354  4116100  2542300  2701800  11273500   774600   4096773
2015-05-07  288448  4486400  1598600  3473100   9992500   636400   4677516
2015-05-08  176330  4471000  2746500  2629300  11390300  1238200   6767632
...            ...      ...      ...      ...       ...      ...       ...
2025-04-28  804300  7708600  1443300  2994500  13890900  2427200   2218800
2025-04-29  586500  5244800  1463600  2539300   9483100  2864900   2339600
2025-04-30  710200  5015900  1922700  4468300  20379300  2701500   3349500
2025-05-01  600300  3875800  1772000  3389100  18610300  1829900   2734600
2025-05-02  589400  3512800  1597200  3854500  16574800  1834700   1972000

Price
Ticker          ZBH     ZBRA      ZTS
Date
2015-05-04  1336631   289700  4782900
2015-05-05  2179686   369200  7681200
2015-05-06  1976982   309500  4441400
2015-05-07  1718349   353400  2427000
2015-05-08  1282041   372100  2548200
...             ...      ...      ...
2025-04-28  1299600  1094500  1873400
2025-04-29   925700  1599800  2065100
2025-04-30  1399600   762600  2926200
2025-05-01  1400700   507800  1930300
2025-05-02  3275100   525800  2654700

[2516 rows x 3521 columns]

In [28]:
all_data.to_csv('../../data/sp500_all_companies.csv')

## Get fundamental data for a specific company

In [2]:
data = yf.Ticker("AAPL")

In [ ]:
bs = data.balance_sheet.transpose()
bs.index = bs.index.strftime('%Y-%m-%d')
bs = bs.to_dict()

income_statement = data.income_stmt.transpose()
income_statement.index = income_statement.index.strftime('%Y-%m-%d')
income_statement = income_statement.to_dict()

diluted_eps = income_statement['Diluted EPS']
book_value = bs['Stockholders Equity']
shares_outstanding = bs['Ordinary Shares Number']

# convert into format we can use
graham_numbers = {}

for date, eps, book_value, shares_outstanding in zip(diluted_eps.keys(), diluted_eps.values(), book_value.values(), shares_outstanding.values()):
    if np.isnan(eps) or np.isnan(book_value) or np.isnan(shares_outstanding):
        continue
    graham_numbers[date] = {}
    book_value_ps = book_value / shares_outstanding
    graham_numbers[date] = (22.5 * eps * book_value_ps) ** 0.5

graham_numbers

# book_value_ps = book_value / shares_outstanding
# (22.5 * diluted_eps * book_value_ps) ** 0.5

{'2024-09-30': 22.701794098299054,
 '2023-09-30': 23.478050809567907,
 '2022-09-30': 20.90282937968418,
 '2021-09-30': 22.017938467373487}

In [50]:
# calculate roe
bs = data.balance_sheet.transpose()
bs.index = bs.index.strftime('%Y-%m-%d')
bs = bs.to_dict()

income_statement = data.income_stmt.transpose()
income_statement.index = income_statement.index.strftime('%Y-%m-%d')
income_statement = income_statement.to_dict()

net_income = income_statement['Net Income']
shareholders = bs['Stockholders Equity']

roe = {}
for date, net_income, shareholders in zip(net_income.keys(), net_income.values(), shareholders.values()):
    if np.isnan(net_income) or np.isnan(shareholders):
        continue
    roe[date] = {}
    roe[date] = net_income / shareholders
roe

{'2024-09-30': 1.6459350307287095,
 '2023-09-30': 1.5607601454639075,
 '2022-09-30': 1.9695887275023682,
 '2021-09-30': 1.5007132667617689}

In [59]:
# calculate P/E ratio
data.info

{'address1': 'One Apple Park Way',
 'city': 'Cupertino',
 'state': 'CA',
 'zip': '95014',
 'country': 'United States',
 'phone': '(408) 996-1010',
 'website': 'https://www.apple.com',
 'industry': 'Consumer Electronics',
 'industryKey': 'consumer-electronics',
 'industryDisp': 'Consumer Electronics',
 'sector': 'Technology',
 'sectorKey': 'technology',
 'sectorDisp': 'Technology',
 'longBusinessSummary': 'Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide. The company offers iPhone, a line of smartphones; Mac, a line of personal computers; iPad, a line of multi-purpose tablets; and wearables, home, and accessories comprising AirPods, Apple TV, Apple Watch, Beats products, and HomePod. It also provides AppleCare support and cloud services; and operates various platforms, including the App Store that allow customers to discover and download applications and digital content, such as books, music, video, games, and podcasts, as well as advertising services include third-party licensing arrangements and its own advertising platforms. In addition, the company offers various subscription-based services, such as Apple Arcade, a game subscription service; Apple Fitness+, a personalized fitness service; Apple Music, which offers users a curated listening experience with on-demand radio stations; Apple News+, a subscription news and magazine service; Apple TV+, which offers exclusive original content; Apple Card, a co-branded credit card; and Apple Pay, a cashless payment service, as well as licenses its intellectual property. The company serves consumers, and small and mid-sized businesses; and the education, enterprise, and government markets. It distributes third-party applications for its products through the App Store. The company also sells its products through its retail and online stores, and direct sales force; and third-party cellular network carriers, wholesalers, retailers, and resellers. Apple Inc. was founded in 1976 and is headquartered in Cupertino, California.',
 'fullTimeEmployees': 150000,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Timothy D. Cook',
   'age': 63,
   'title': 'CEO & Director',
   'yearBorn': 1961,
   'fiscalYear': 2023,
   'totalPay': 16239562,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Jeffrey E. Williams',
   'age': 60,
   'title': 'Chief Operating Officer',
   'yearBorn': 1964,
   'fiscalYear': 2023,
   'totalPay': 4637585,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Katherine L. Adams',
   'age': 60,
   'title': 'Senior VP, General Counsel & Secretary',
   'yearBorn': 1964,
   'fiscalYear': 2023,
   'totalPay': 4618064,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': "Ms. Deirdre  O'Brien",
   'age': 57,
   'title': 'Chief People Officer & Senior VP of Retail',
   'yearBorn': 1967,
   'fiscalYear': 2023,
   'totalPay': 4613369,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Kevan  Parekh',
   'age': 52,
   'title': 'Senior VP & CFO',
   'yearBorn': 1972,
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Chris  Kondo',
   'title': 'Senior Director of Corporate Accounting',
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Suhasini  Chandramouli',
   'title': 'Director of Investor Relations',
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Kristin Huguet Quayle',
   'title': 'Vice President of Worldwide Communications',
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Greg  Joswiak',
   'title': 'Senior Vice President of Worldwide Marketing',
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Adrian  Perica',
   'age': 50,
   'title': 'Vice President of Corporate Development',
   'yearBorn': 1974,
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 7,
 'boardRisk': 1,
 'compensationRisk': 3,
 'shareHolderRightsRisk': 1,
 'overallRisk': 1,
 'governanceEpochDate': 1740787200,
 'compensationAsOfEpochDate': 1703980800,
 'irWebsite': 'http://investor.apple.com/',
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 223.85,
 'open': 221.649,
 'dayLow': 217.68,
 'dayHigh': 223.8,
 'regularMarketPreviousClose': 223.85,
 'regularMarketOpen': 221.649,
 'regularMarketDayLow': 217.68,
 'regularMarketDayHigh': 223.8,
 'dividendRate': 1.0,
 'dividendYield': 0.46,
 'exDividendDate': 1739145600,
 'payoutRatio': 0.1571,
 'fiveYearAvgDividendYield': 0.59,
 'beta': 1.178,
 'trailingPE': 34.5873,
 'forwardPE': 26.221418,
 'volume': 39525987,
 'regularMarketVolume': 39525987,
 'averageVolume': 52532506,
 'averageVolume10days': 47802000,
 'averageDailyVolume10Day': 47802000,
 'bid': 217.76,
 'ask': 217.84,
 'bidSize': 4,
 'askSize': 2,
 'marketCap': 3273315581952,
 'fiftyTwoWeekLow': 164.08,
 'fiftyTwoWeekHigh': 260.1,
 'priceToSalesTrailing12Months': 8.270961,
 'fiftyDayAverage': 230.3722,
 'twoHundredDayAverage': 229.0202,
 'trailingAnnualDividendRate': 0.99,
 'trailingAnnualDividendYield': 0.0044226046,
 'currency': 'USD',
 'tradeable': False,
 'enterpriseValue': 3316333674496,
 'profitMargins': 0.24295,
 'floatShares': 14998187904,
 'sharesOutstanding': 15022100480,
 'sharesShort': 129678474,
 'sharesShortPriorMonth': 127893856,
 'sharesShortPreviousMonthDate': 1739491200,
 'dateShortInterest': 1741910400,
 'sharesPercentSharesOut': 0.0086,
 'heldPercentInsiders': 0.0207,
 'heldPercentInstitutions': 0.62836,
 'shortRatio': 2.54,
 'shortPercentOfFloat': 0.0086,
 'impliedSharesOutstanding': 15172599808,
 'bookValue': 4.438,
 'priceToBook': 49.09869,
 'lastFiscalYearEnd': 1727481600,
 'nextFiscalYearEnd': 1759017600,
 'mostRecentQuarter': 1735344000,
 'earningsQuarterlyGrowth': 0.071,
 'netIncomeToCommon': 96150003712,
 'trailingEps': 6.3,
 'forwardEps': 8.31,
 'lastSplitFactor': '4:1',
 'lastSplitDate': 1598832000,
 'enterpriseToRevenue': 8.38,
 'enterpriseToEbitda': 24.145,
 '52WeekChange': 0.2815386,
 'SandP52WeekChange': 0.06429911,
 'lastDividendValue': 0.25,
 'lastDividendDate': 1739145600,
 'quoteType': 'EQUITY',
 'currentPrice': 217.9,
 'targetHighPrice': 325.0,
 'targetLowPrice': 197.0,
 'targetMeanPrice': 252.59052,
 'targetMedianPrice': 255.0,
 'recommendationMean': 2.02222,
 'recommendationKey': 'buy',
 'numberOfAnalystOpinions': 39,
 'totalCash': 53774999552,
 'totalCashPerShare': 3.58,
 'ebitda': 137352003584,
 'totalDebt': 96798998528,
 'quickRatio': 0.783,
 'currentRatio': 0.923,
 'totalRevenue': 395760009216,
 'debtToEquity': 145.0,
 'revenuePerShare': 25.974,
 'returnOnAssets': 0.22518998,
 'returnOnEquity': 1.3652,
 'grossProfits': 184102993920,
 'freeCashflow': 93833871360,
 'operatingCashflow': 108293996544,
 'earningsGrowth': 0.101,
 'revenueGrowth': 0.04,
 'grossMargins': 0.46519002,
 'ebitdaMargins': 0.34706002,
 'operatingMargins': 0.34459,
 'financialCurrency': 'USD',
 'symbol': 'AAPL',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Nasdaq Real Time Price',
 'triggerable': True,
 'customPriceAlertConfidence': 'HIGH',
 'shortName': 'Apple Inc.',
 'corporateActions': [],
 'postMarketTime': 1743206395,
 'regularMarketTime': 1743192001,
 'exchange': 'NMS',
 'messageBoardId': 'finmb_24937',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'gmtOffSetMilliseconds': -14400000,
 'market': 'us_market',
 'esgPopulated': False,
 'longName': 'Apple Inc.',
 'hasPrePostMarketData': True,
 'firstTradeDateMilliseconds': 345479400000,
 'postMarketChangePercent': -0.312066,
 'postMarketPrice': 217.22,
 'postMarketChange': -0.679993,
 'regularMarketChange': -5.950012,
 'regularMarketDayRange': '217.68 - 223.8',
 'fullExchangeName': 'NasdaqGS',
 'averageDailyVolume3Month': 52532506,
 'fiftyTwoWeekLowChange': 53.819992,
 'fiftyTwoWeekLowChangePercent': 0.32801068,
 'fiftyTwoWeekRange': '164.08 - 260.1',
 'fiftyTwoWeekHighChange': -42.200012,
 'fiftyTwoWeekHighChangePercent': -0.16224533,
 'fiftyTwoWeekChangePercent': 28.15386,
 'dividendDate': 1739404800,
 'earningsTimestamp': 1738272600,
 'earningsTimestampStart': 1746010740,
 'earningsTimestampEnd': 1746446400,
 'earningsCallTimestampStart': 1738274400,
 'earningsCallTimestampEnd': 1738274400,
 'isEarningsDateEstimate': True,
 'epsTrailingTwelveMonths': 6.3,
 'epsForward': 8.31,
 'epsCurrentYear': 7.32671,
 'priceEpsCurrentYear': 29.740496,
 'fiftyDayAverageChange': -12.4721985,
 'fiftyDayAverageChangePercent': -0.05413934,
 'twoHundredDayAverageChange': -11.120209,
 'twoHundredDayAverageChangePercent': -0.04855558,
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 0,
 'averageAnalystRating': '2.0 - Buy',
 'cryptoTradeable': False,
 'regularMarketChangePercent': -2.6580353,
 'regularMarketPrice': 217.9,
 'marketState': 'CLOSED',
 'displayName': 'Apple',
 'trailingPegRatio': 2.0223}

In [10]:
d = data.income_stmt.to_dict(orient='index')
d['Diluted EPS'].values()

dict_values([6.08, 6.13, 6.11, 5.61, nan])

In [55]:
data.balance_sheet.index

Index(['Treasury Shares Number', 'Ordinary Shares Number', 'Share Issued',
       'Net Debt', 'Total Debt', 'Tangible Book Value', 'Invested Capital',
       'Working Capital', 'Net Tangible Assets', 'Capital Lease Obligations',
       'Common Stock Equity', 'Total Capitalization',
       'Total Equity Gross Minority Interest', 'Stockholders Equity',
       'Gains Losses Not Affecting Retained Earnings',
       'Other Equity Adjustments', 'Retained Earnings', 'Capital Stock',
       'Common Stock', 'Total Liabilities Net Minority Interest',
       'Total Non Current Liabilities Net Minority Interest',
       'Other Non Current Liabilities', 'Tradeand Other Payables Non Current',
       'Long Term Debt And Capital Lease Obligation',
       'Long Term Capital Lease Obligation', 'Long Term Debt',
       'Current Liabilities', 'Other Current Liabilities',
       'Current Deferred Liabilities', 'Current Deferred Revenue',
       'Current Debt And Capital Lease Obligation',
       'Current Capital Lease Obligation', 'Current Debt',
       'Other Current Borrowings', 'Commercial Paper',
       'Payables And Accrued Expenses', 'Payables', 'Total Tax Payable',
       'Income Tax Payable', 'Accounts Payable', 'Total Assets',
       'Total Non Current Assets', 'Other Non Current Assets',
       'Non Current Deferred Assets', 'Non Current Deferred Taxes Assets',
       'Investments And Advances', 'Other Investments',
       'Investmentin Financial Assets', 'Available For Sale Securities',
       'Net PPE', 'Accumulated Depreciation', 'Gross PPE', 'Leases',
       'Other Properties', 'Machinery Furniture Equipment',
       'Land And Improvements', 'Properties', 'Current Assets',
       'Other Current Assets', 'Inventory', 'Receivables', 'Other Receivables',
       'Accounts Receivable',
       'Cash Cash Equivalents And Short Term Investments',
       'Other Short Term Investments', 'Cash And Cash Equivalents',
       'Cash Equivalents', 'Cash Financial'],
      dtype='object')

In [ ]:
net_income = data.income_stmt.loc['Net Income']
equity = data.balance_sheet.loc['Stockholders Equity']

2024-09-30   -19154000000.0
2023-09-30     -214000000.0
2022-09-30    -3068000000.0
2021-09-30     5562000000.0
2020-09-30              NaN
Name: Retained Earnings, dtype: object

In [41]:
equity

2024-09-30    56950000000.0
2023-09-30    62146000000.0
2022-09-30    50672000000.0
2021-09-30    63090000000.0
2020-09-30              NaN
Name: Stockholders Equity, dtype: object

In [44]:
(net_income / equity).dropna()

2024-09-30    1.645935
2023-09-30     1.56076
2022-09-30    1.969589
2021-09-30    1.500713
dtype: object

In [82]:
# could maybe write a function to get news about the company, then get the LLM to link it in its response
news = data.news

news[1]['content']['clickThroughUrl']['url']

'https://finance.yahoo.com/news/tech-support-apples-macbook-air-is-100-cheaper-and-still-among-the-best-laptops-you-can-buy-143011864.html'

In [4]:
def get_balance_sheet(ticker: str) -> dict:
    '''
    Get the balance sheet of the company given a ticker symbol.
    
    Potentially useful fields include:
        - Stockholders Equity
        - Retained Earnings
        - Total Assets
        - Net PPE
        - Gross PPE
        - Common Stock Equity
        - Total Debt
        - Tangible Book Value
        - Invested Capital
        - Cash And Cash Equivalents
        - Total Debt
        - Common Stock Equity
        - Current Assets
        - Current Liabilities
        - Receivables
        - Total Liabilities Net Minority Interest
        - Capital Lease Obligations
        - Working Capital
        - Accounts Receivable
        - Inventory
        - Cash Cash Equivalents And Short Term Investments
        - Other Short Term Investments

    Args:
        ticker (str): The ticker symbol of the company

    Returns:
        dict: The balance sheet of the company
    '''
    
    stock = yf.Ticker(ticker)
    bs = stock.balance_sheet.transpose()
    bs.index = bs.index.strftime('%Y-%m-%d')

    return bs.to_dict()

def get_income_statement(ticker: str) -> dict:
    '''
    Get the income statement of the company given a ticker symbol.

    Potentially useful fields include:
        - Revenue
        - Cost Of Goods Sold
        - Gross Profit
        - Operating Income
        - Net Income
        - Earnings Before Interest And Taxes (EBIT)
        - Earnings Before Interest Taxes Depreciation And Amortization (EBITDA)
        - Earnings Before Interest And Taxes (EBIT)
        - Earnings Before Interest Taxes Depreciation And Amortization (EBITDA)

    Args:
        ticker (str): The ticker symbol of the company

    Returns:
        dict: The income statement of the company
    '''
    
    stock = yf.Ticker(ticker)
    income_statement = stock.income_stmt.transpose()
    income_statement.index = income_statement.index.strftime('%Y-%m-%d')

    return income_statement.to_dict()

def get_cash_flow(ticker: str) -> dict:
    '''
    Get the cash flow statement of the company given a ticker symbol.

    Potentially useful fields include:
        - Operating Cash Flow
        - Investing Cash Flow
        - Financing Cash Flow
        - Free Cash Flow

    Args:
        ticker (str): The ticker symbol of the company

    Returns:
        dict: The cash flow statement of the company
    '''
    stock = yf.Ticker(ticker)
    cash_flow = stock.cash_flow.transpose()
    cash_flow.index = cash_flow.index.strftime('%Y-%m-%d')

    return cash_flow.to_dict()

In [10]:
ticker = yf.Ticker('AAPL')

ticker.get_shares_outstanding()

AttributeError: 'Ticker' object has no attribute 'get_shares_outstanding'

In [ ]:
import yfinance as yf
import pandas as pd

def get_pe_ratio(ticker: str) -> list:
    '''
    Get the P/E ratio of the company given a ticker symbol.

    Args:
        ticker (str): The ticker symbol of the company

    Returns:
        list: A list P/E ratios for each year
    '''
    
    income_statement = get_income_statement(ticker)
    eps = income_statement['Diluted EPS']

    stock = yf.Ticker(ticker)
    prices = stock.history(period='max')
    prices['year'] = prices.index.year
    year_last_prices = prices.groupby('year').last()['Close']

    pe_ratios = []
    for date, eps in eps.items():
        if np.isnan(eps):
            pe_ratios.append((date, 'Unknown'))
            continue
        year = pd.to_datetime(date).year
        if year in year_last_prices.index:
            pe_ratio = year_last_prices[year] / eps
            pe_ratios.append((date, round(pe_ratio, 2)))

    return pe_ratios


income_statement = get_income_statement('AAPL')
net_income = income_statement['Net Income']

# 3. Calculate P/E ratio for each year
# Merge price data with earnings data (using year-end prices)
stock = yf.Ticker("AAPL")
prices = stock.history(period='max')
prices['year'] = prices.index.year
year_last_prices = prices.groupby('year').last()['Close']

eps = income_statement['Diluted EPS']
pe_ratios = []

for date, eps in eps.items():
    if np.isnan(eps):
        pe_ratios.append((date, 'Unknown'))
        continue
    year = pd.to_datetime(date).year
    if year in year_last_prices.index:
        pe_ratio = year_last_prices[year] / eps
        pe_ratios.append((date, round(pe_ratio, 2)))


# year_last_prices / earnings

# pe_ratios = pd.DataFrame({
#     'Price': year_end_prices,
#     'Earnings': earnings['Earnings'],
#     'P/E Ratio': year_end_prices / earnings['Earnings']
# })

# print(pe_ratios)

# stock = yf.Ticker("AMZN")
# shares_outstanding = stock.get_shares_full(start=list(net_income.keys())[-1], end=list(net_income.keys())[0])
# shares_outstanding.index = pd.to_datetime(shares_outstanding.index)
# shares_outstanding.groupby(shares_outstanding.index).last()
# shares_outstanding.index = shares_outstanding.index.strftime('%Y-%m-%d')

# eps = income_statement['Diluted EPS']

In [74]:
pe_ratios

[('2024-09-30', 41.14),
 ('2023-09-30', 31.22),
 ('2022-09-30', 21.02),
 ('2021-09-30', 31.11),
 ('2020-09-30', 'Unknown')]